<?php
/**
 * Default options for WP Customizer
 */
$elletta_customizer_defaults = array(
        // Settings
        'pagination_type'                     => 'numeric',
        'logo_text'                           => 'Elletta Theme',
        'logo_text_color'                     => '#333333',
        'pattern_page'                        => 'pattern-0',
        'header_style'                        => 'header-1',
        'show_logo'                           => true,
        // Header.
        'header_show_search'                  => true,
        'header_show_social_icons'            => false,
        'primary_menu_font_size'              => 12,
        'primary_submenu_font_size'           => 10,
        'primary_menu_background_color'       => '#FFFFFF',
        'primary_menu_text_color'             => '#333333',
        'primary_menu_text_color_hover'       => '#00B2B5',
        'primary_menu_submenu_background_color' => '#FFFFFF',
        'primary_menu_submenu_text_color'       => '#333333',
        'primary_menu_submenu_text_color_hover' => '#00B2B5',
        'secondary_menu_font_size'              => 10,
        'secondary_submenu_font_size'           => 10,
        'secondary_menu_background_color'       => '#333333',
        'secondary_menu_text_color'             => '#AAAAAA',
        'secondary_menu_text_color_hover'       => '#00B2B5',
        'secondary_menu_submenu_background_color' => '#FFFFFF',
        'secondary_menu_submenu_text_color'       => '#333333',
        'secondary_menu_submenu_text_color_hover' => '#00B2B5',
        'mobile_menu_font_size'              => 12,
        'mobile_submenu_font_size'           => 10,
        'mobile_menu_background_color'       => '#FFFFFF',
        'mobile_menu_text_color'             => '#333333',
        'mobile_menu_text_color_hover'       => '#00B2B5',
        'mobile_submenu_background_color' => '#FFFFFF',
        'mobile_submenu_text_color'       => '#333333',
        'mobile_submenu_text_color_hover' => '#00B2B5',
        // Home Slider
        'show_slider'                         => true,
        'boxed_slider'                        => true,       
        'hide_mobile_slider'                  => false,
        'height_slider'                       => 500,
        'slider_transition'                   => 'slide',
        'autoplay_slider'                     => true,
        'show_author_slider'                  => true,
        'show_categories_slider'              => true,
        'show_date_slider'                    => true,  
        'title_slider_font_size'              => 33,
        'slider_posts'                        => 'lastest_posts',
        'number_posts'                        => 4,
        //Home
        'sidebar_homepage'                    => 'right',
        'layout_homepage'                     => 'grid-nofeatured',
        //Page
        'sidebar_page'                        => 'right',
        'layout_page'                         => 'grid',
        'show_comments_page'                  => true,
        //Woocommerce
        'sidebar_woocommerce'                 => 'right',
        'sidebar_woocommerce_list'            => 'right',
        //Events Calendar
        'sidebar_events'                      => 'right',
        //Footer
        'footer_boxed'                        => false,
        'footer_newsletter_show'              => false,
        'footer_newsletter_title'             => 'STAY UPDATED',
        'footer_newsletter_subtitle'          => 'WE LIKE TO SHARE LATEST NEWS OF ELLETTA',
        'footer_newsletter_text_color'        => '#FFFFFF',
        'footer_newsletter_bg_image'          => 'http://elletta.tuweb4.com/wp-content/themes/elletta/images/newsletter-background.jpg',
        'footer_newsletter_background_color'  => '#F7F7F7',
        'footer_instagram_show'               => true,
        'footer_widget_area_show'             => true,
        'footer_columns'                      => 3,
        'footer_copyright'                    => 'Elletta Theme - From Spain with love - info@tuweb4.com Copyright - 2016 tuweb4, Inc',
        'footer_background_color'             => '#FFFFFF',
        'footer_font_color'                   => '#1C193C',
        'footer_title_font_color'             => '#191939',
        'footer_copyright_show'               => true,
        'footer_logo'                         => 'http://elletta.tuweb4.com/wp-content/themes/elletta/images/footer-logo.png',
        'footer_social_media'                 => true,
        //Social Media
        'elletta_facebook'                     => '#',
        'elletta_twitter'                      => '#',
        'elletta_instagram'                    => '#',
        'elletta_pinterest'                    => '',
        'elletta_bloglovin'                    => '',
        'elletta_google_plus'                  => '#',
        'elletta_tumblr'                       => '',
        'elletta_youtube'                      => '#',
        'elletta_linkedin'                     => '',
        //Posts
        'sidebar_post'                        => 'right',
        'show_categories_post'                => true,
        'show_date_post'                      => true,
        'show_author_post'                    => true,
        'show_author_box_post'                => true,
        'show_tags_post'                      => true,
        'show_share_buttons_post'             => true,
        'show_related_posts_post'             => true,
        'show_post_navigation_post'           => true,
        'show_comments_post'                  => true,
        'show_views_post'                     => true,
        //Featured Area
        'show_featured_area'                  => true,
        'featured_area_columns'               => 3,
        'category_posts_featured_area'        => 0,
        'show_categories_featured_area'       => true,
        'show_date_featured_area'             => true,
        'title_featured_font_size'            => 24,
        //Fonts
        'body_font_size'                      => 14,
        'title_post_font_size'                => 35,
        'title_list_font_size'                => 33,
        'title_widget_font_size'              => 18,
        'body_font_weight'                    => 100,
        'title_font_weight'                   => 700,
        'header_font_weight'                  => 700,
        //Colors
        'body_background_color'               => '#F7F7F7',
        'body_text_color'                     => '#2C2C2C',
        'title_text_color'                    => '#1B193B',
        'title_widget_text_color'             => '#1A193A',
        'link_text_color'                     => '#00A8B5',
        'link_hover_text_color'               => '#2C2C2C',
        'button_read_more_color'              => '#CECECE',
        'button_read_more_text_color'         => '#000000',
        'other_buttons_color'                 => '#00A8B5',
        'other_buttons_text_color'            => '#FFFFFF',
        'tags_categories_color'               => '#00A8B5',
        'tags_categories_text_color'          => '#FFFFFF',
        'comments_background_color'           => '#FFFFFF'
);